// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318165823_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Api.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyOrProject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("IsActive");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium noise-cancelling headphones with 30-hour battery life",
                            ImageUrl = "https://example.com/images/headphones.jpg",
                            IsActive = true,
                            Name = "Wireless Bluetooth Headphones",
                            Price = 149.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Category = "Furniture",
                            CreatedAt = new DateTime(2026, 1, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Adjustable lumbar support with breathable mesh back",
                            ImageUrl = "https://example.com/images/chair.jpg",
                            IsActive = true,
                            Name = "Ergonomic Office Chair",
                            Price = 299.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 3,
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2026, 1, 17, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Double-walled insulated bottle, keeps drinks cold for 24 hours",
                            ImageUrl = "https://example.com/images/bottle.jpg",
                            IsActive = true,
                            Name = "Stainless Steel Water Bottle",
                            Price = 34.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 4,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 18, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "RGB backlit with Cherry MX switches",
                            ImageUrl = "https://example.com/images/keyboard.jpg",
                            IsActive = true,
                            Name = "Mechanical Gaming Keyboard",
                            Price = 129.99m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 5,
                            Category = "Sports",
                            CreatedAt = new DateTime(2026, 1, 19, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Extra thick non-slip exercise mat with carrying strap",
                            ImageUrl = "https://example.com/images/yogamat.jpg",
                            IsActive = true,
                            Name = "Yoga Mat Premium",
                            Price = 45.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 6,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fitness tracking, heart rate monitor, GPS enabled",
                            ImageUrl = "https://example.com/images/smartwatch.jpg",
                            IsActive = true,
                            Name = "Smart Watch Pro",
                            Price = 249.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 7,
                            Category = "Furniture",
                            CreatedAt = new DateTime(2026, 1, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Adjustable height desk riser for improved ergonomics",
                            ImageUrl = "https://example.com/images/deskconverter.jpg",
                            IsActive = true,
                            Name = "Standing Desk Converter",
                            Price = 179.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 8,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 22, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "20000mAh power bank with fast charging support",
                            ImageUrl = "https://example.com/images/powerbank.jpg",
                            IsActive = true,
                            Name = "Portable Phone Charger",
                            Price = 49.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 9,
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2026, 1, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "12-cup programmable coffee maker with thermal carafe",
                            ImageUrl = "https://example.com/images/coffeemaker.jpg",
                            IsActive = true,
                            Name = "Coffee Maker Deluxe",
                            Price = 89.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 10,
                            Category = "Sports",
                            CreatedAt = new DateTime(2026, 1, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "5 different resistance levels for home workouts",
                            ImageUrl = "https://example.com/images/resistancebands.jpg",
                            IsActive = false,
                            Name = "Resistance Bands Set",
                            Price = 24.99m,
                            StockQuantity = 200
                        });
                });

            modelBuilder.Entity("Api.Models.VisitMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Route", "Date")
                        .IsUnique();

                    b.ToTable("VisitMetrics");
                });
#pragma warning restore 612, 618
        }
    }
}
