name: Deploy to S3 + CloudFront

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install (client)
        working-directory: client
        run: npm ci

      - name: Build (client)
        working-directory: client
        run: npm run build

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::305137865693:role/github-deploy-justingritten-dev
          aws-region: us-east-2

      - name: Deploy to S3
        run: aws s3 sync ./client/dist s3://justingritten.dev --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id E3D56KG355201F --paths "/*"